package dominio;
// Generated 10/04/2015 20:10:32 by Hibernate Tools 3.6.0



/**
 * Contato generated by hbm2java
 */
public class Contato  implements java.io.Serializable {


     private int id;
     private String nome;
     private String telefone;
     private String email;

    public Contato() {
    }

	
    public Contato(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public Contato(int id, String nome, String telefone, String email) {
       this.id = id;
       this.nome = nome;
       this.telefone = telefone;
       this.email = email;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


